name: monitor_rpg
description: Pip-Boy 2000 style companion app for tabletop RPG
publish_to: "none"
version: 0.6.0+6

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  device_info_plus: ^10.1.0
  battery_plus: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

